version: '3.7'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - mysql_ls
    container_name: purchase_web_server
  mysql_ls:
    image: mysql:5.7
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=purchases
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password2019
    ports:
      - 33061:3306
    container_name: mysql_ls
  phpmyadmin_gas:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_ls
    ports:
      - 9990:80
    links:
      - mysql_ls:db
