# Generated by Django 2.2.12 on 2020-05-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите номер сделки (может включать буквы, цифры и другие знаки)', max_length=200)),
                ('date', models.DateField(help_text='Дата сделки')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('number', models.TextField(help_text='Введите номер закупки', verbose_name='Номер закупки')),
                ('date', models.DateField(help_text='Введите дату осуществления закупки')),
                ('deal', models.ManyToManyField(help_text='Выберите номер сделки', to='purchase.Deal')),
            ],
        ),
    ]
