# Generated by Django 2.2.12 on 2020-05-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='number',
            field=models.TextField(help_text='Введите номер закупки', max_length=20, verbose_name='Номер закупки'),
        ),
    ]
