# Generated by Django 2.2.12 on 2020-05-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_auto_20200517_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='number',
            field=models.CharField(help_text='Введите номер закупки', max_length=20, verbose_name='Номер закупки'),
        ),
    ]
