# Generated by Django 2.2.12 on 2020-05-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_auto_20200517_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='date',
            field=models.DateField(help_text='Дата сделки', verbose_name='Дата сделки'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='name',
            field=models.CharField(help_text='Введите номер сделки (может включать буквы, цифры и другие знаки)', max_length=200, verbose_name='Номер сделки'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(help_text='Введите дату осуществления закупки', verbose_name='Дфта закупки'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='deal',
            field=models.ManyToManyField(help_text='Выберите номер сделки', related_name='Сделка', to='purchase.Deal'),
        ),
    ]
