# Generated by Django 2.2.12 on 2020-05-17 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_auto_20200517_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(help_text='Введите дату осуществления закупки', verbose_name='Дата закупки'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='deal',
            field=models.ManyToManyField(help_text='Выберите номер сделки', to='purchase.Deal'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Наименование закупки'),
        ),
    ]
