# Generated by Django 2.2.12 on 2020-05-17 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_auto_20200517_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Введите номер договора', max_length=20, verbose_name='Номер договора')),
                ('document', models.FileField(help_text='Выберите файл', upload_to='', verbose_name='Документ')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование поставки')),
                ('number', models.CharField(max_length=100, verbose_name='Номер поставки')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата поставки')),
                ('purchase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.Purchase')),
            ],
        ),
        migrations.CreateModel(
            name='Storehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите наименование склада', max_length=50, verbose_name='Наименование склада')),
                ('phone', models.CharField(help_text='Введите номер телефона склада', max_length=18, verbose_name='Номер телефона')),
                ('address', models.TextField(help_text='Введите адрес склада', max_length=200, verbose_name='Адрес склада')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите наименование поставщика', max_length=50, verbose_name='Наименование поставщика')),
                ('phone', models.CharField(help_text='Введите номер телефона поставщика', max_length=18, verbose_name='Номер телефона')),
                ('address', models.TextField(help_text='Введите адрес поставщика', max_length=200, verbose_name='Адрес поставищка')),
            ],
        ),
        migrations.AlterField(
            model_name='deal',
            name='date',
            field=models.DateField(help_text='Введите дату сделки', verbose_name='Дата сделки'),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование приемка')),
                ('number', models.CharField(max_length=100, verbose_name='Номер приемки')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата поставки')),
                ('delivery', models.ForeignKey(help_text='Выберите номер поставки', null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.Delivery')),
                ('storehouse', models.ForeignKey(help_text='Выберите склад', null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.Storehouse')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.Contract'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='vendor',
            field=models.ManyToManyField(help_text='Выберите поставщика', to='purchase.Vendor'),
        ),
    ]
