# Generated by Django 2.2.12 on 2020-05-17 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_auto_20200517_0826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Договора на закупку'},
        ),
        migrations.AlterModelOptions(
            name='deal',
            options={'verbose_name': 'Сделки'},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Поставки'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Закупки'},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'verbose_name': 'Приемки'},
        ),
        migrations.AlterModelOptions(
            name='storehouse',
            options={'verbose_name': 'Склады'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name': 'Поставщики'},
        ),
        migrations.RemoveField(
            model_name='contract',
            name='document',
        ),
    ]
