# Generated by Django 2.2.12 on 2020-05-22 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_auto_20200517_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='document',
            field=models.FileField(help_text='Выберите файл', null=True, upload_to='uploads/', verbose_name='Ссылка на документ'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.Purchase', verbose_name='Закупки'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.Contract', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='delivery',
            field=models.ForeignKey(help_text='Выберите номер поставки', null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.Delivery', verbose_name='Поставки'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование приемки'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='storehouse',
            field=models.ForeignKey(help_text='Выберите склад', null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.Storehouse', verbose_name='Склады'),
        ),
    ]
